// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awifqchcmsgjzzlvaizd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3aWZxY2hjbXNnanp6bHZhaXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MjYwOTIsImV4cCI6MjA2ODUwMjA5Mn0.Cn2ld_BgYcwBGXpwzN_rT5aBAMYCyzrXEPwQeO_A93E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});